---
apiVersion: v1
kind: Service
metadata:
  name: fdk-dataset-postman
  namespace: demo
spec:
  selector:
    app: fdk-dataset-postman
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
