[package]
name = "fdk-rdf-postman"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
futures = "0.3.24"
lazy_static = "1.4.0"
rdkafka = "0.28.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber =  { version = "0.3.11", features = ["json"] }
