---
apiVersion: v1
kind: Service
metadata:
  name: fdk-data-service-postman
spec:
  selector:
    app: fdk-data-service-postman
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
