---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - concept-deployment.yaml
  - concept-service.yaml
  - data-service-service.yaml
  - data-service-deployment.yaml
  - dataset-deployment.yaml
  - dataset-service.yaml
images:
  - name: fdk-rdf-postman
    newName: eu.gcr.io/digdir-fdk-infra/fdk-rdf-postman
    newTag: $(GIT_COMMIT_SHA)
